[phases.setup]
nixPkgs = ["chromium", "chromedriver", "python311"]

[phases.install]
cmds = [
  "python3.11 -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/gunicorn -w 1 --threads 8 -b 0.0.0.0:$PORT app:app"
